import os
import sqlite3

import psycopg
from psycopg.rows import dict_row
DatabaseIntegrityError = (sqlite3.IntegrityError, psycopg.IntegrityError)

BASE = os.path.dirname(os.path.abspath(__file__))
SQLITE_DB = os.path.join(BASE, "sizeplus.db")

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()


def database_backend():
    return "postgresql" if DATABASE_URL else "sqlite"


def _pg_sql(sql):
    """
    Translate SQLite-style parameter placeholders used by the
    existing Sizeplus application into psycopg placeholders.
    """
    return sql.replace("?", "%s")


class PostgresCursor:
    def __init__(self, cursor):
        self._cursor = cursor
        self.lastrowid = None

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def __iter__(self):
        return iter(self._cursor)


class PostgresConnection:
    def __init__(self, connection):
        self._connection = connection
    def execute(self, sql, params=None):
        cur = self._connection.cursor()
        translated_sql = _pg_sql(sql)

        # Preserve SQLite cursor.lastrowid behaviour for PostgreSQL
        # inserts into identity-based tables.
        is_insert = translated_sql.lstrip().upper().startswith("INSERT INTO")
        has_returning = " RETURNING " in translated_sql.upper()

        if is_insert and not has_returning:
            table_name = translated_sql.lstrip().split()[2].strip('"').lower()

            identity_tables = {
                "users",
                "products",
                "variants",
                "product_images",
                "customers",
                "sales",
                "sale_items",
                "stock_movements",
                "orders",
                "order_items",
                "audit_logs",
            }

            if table_name in identity_tables:
                translated_sql = translated_sql.rstrip().rstrip(";") + " RETURNING id"

        if params is None:
            cur.execute(translated_sql)
        else:
            cur.execute(translated_sql, params)

        wrapped = PostgresCursor(cur)

        if is_insert and " RETURNING id" in translated_sql.upper():
            row = cur.fetchone()
            if row:
                wrapped.lastrowid = row["id"]

        return wrapped
    def executescript(self, script):
        """
        Execute the existing SQLite schema script on PostgreSQL
        after translating SQLite-specific primary-key syntax.
        """
        script = script.replace(
            "INTEGER PRIMARY KEY AUTOINCREMENT",
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        )

        cur = self._connection.cursor()

        for statement in script.split(";"):
            statement = statement.strip()
            if statement:
                cur.execute(statement)

        return PostgresCursor(cur)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def conn():
    """
    Return the active database connection.

    SQLite:
        Local development fallback.

    PostgreSQL:
        Render production database using a compatibility wrapper
        for the application's existing SQLite-style placeholders.
    """

    if DATABASE_URL:
        connection = psycopg.connect(
            DATABASE_URL,
            row_factory=dict_row,
        )
        return PostgresConnection(connection)

    connection = sqlite3.connect(SQLITE_DB)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys=ON")
    return connection